apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  labels:
    app: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      serviceAccountName: airflow
      containers:
        - name: scheduler-pod
          image: nhatthai/airflow-k8s-executor:latest
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - echo "Executing - airflow initdb";
              airflow initdb;
              echo "Starting - airflow scheduler";
              airflow scheduler;
          envFrom:
            - configMapRef:
                name: airflow-variables
          env:
            - name: AIRFLOW__KUBERNETES__ENV_FROM_CONFIGMAP_REF
              value: airflow-variables