# ---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-service
  labels:
    run: postgres-service
spec:
  containers:
    - name: postgres-service
      image: postgres:12
      ports:
        - containerPort: 5432
          protocol: TCP
      env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: airflow-variables
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: airflow-variables
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: airflow-variables
              key: POSTGRES_PASSWORD